# Generated by Django 4.2.11 on 2024-05-06 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Gender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('poster', models.ImageField(blank=True, upload_to='media/')),
                ('number_of_seasons', models.PositiveIntegerField()),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='Gender.gender')),
            ],
        ),
    ]
